In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [4]:
df.info() #to find out datatypes of of the attributes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [5]:
df.describe().T #to get the statistical description of attributes that aren't objects

count         mean          std    min     25%     50%  \
ApplicantIncome    614.0  5403.459283  6109.041673  150.0  2877.5  3812.5   
CoapplicantIncome  614.0  1621.245798  2926.248369    0.0     0.0  1188.5   
LoanAmount         592.0   146.412162    85.587325    9.0   100.0   128.0   
Loan_Amount_Term   600.0   342.000000    65.120410   12.0   360.0   360.0   
Credit_History     564.0     0.842199     0.364878    0.0     1.0     1.0   

                       75%      max  
ApplicantIncome    5795.00  81000.0  
CoapplicantIncome  2297.25  41667.0  
LoanAmount          168.00    700.0  
Loan_Amount_Term    360.00    480.0  
Credit_History        1.00      1.0

In [6]:
df.describe(include=['O']).T #to get the statistical description of attributes that are objects

count unique        top freq
Loan_ID         614    614   LP001754    1
Gender          601      2       Male  489
Married         611      2        Yes  398
Dependents      599      4          0  345
Education       614      2   Graduate  480
Self_Employed   582      2         No  500
Property_Area   614      3  Semiurban  233
Loan_Status     614      2          Y  422

In [7]:
df.isnull().sum() #finding number of rows with NaN data

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
nanVals = df.isnull()  #finding all rows with NaN values
rowsWithNan = nanVals.any(axis=1)
rowsWithNan = df[rowsWithNan]
print(rowsWithNan) 

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
16   LP001034    Male      No          1  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
23   LP001050     NaN     Yes          2  Not Graduate            No   
..        ...     ...     ...        ...           ...           ...   
592  LP002933     NaN      No         3+      Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
600  LP002949  Female      No         3+      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
605  LP002960    Male     Yes          0  Not Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN           

## Data Pre-Processing

In [9]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [10]:
df['Gender'].unique() #binary data

array(['Male', 'Female', nan], dtype=object)

In [11]:
df['Married'].unique() #binary data

array(['No', 'Yes', nan], dtype=object)

In [12]:
df['Dependents'].unique() #ordinal data

array(['0', '1', '2', '3+', nan], dtype=object)

In [13]:
df['Self_Employed'].unique() #binary data

array(['No', 'Yes', nan], dtype=object)

In [14]:
df['LoanAmount'].unique() #numerical data

array([ nan, 128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70.,
       109., 200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315.,
       116., 112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320.,
       144., 184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97.,
       135., 180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187.,
       113., 176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,
        25., 137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,
        85., 259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242.,
       129.,  30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87.,
       101., 495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,
        90., 166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,
        42., 280., 140., 155., 123., 279., 192., 304., 330., 150., 207.,
       436.,  78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300.,
       376., 117.,  71., 490., 173.,  46., 228., 30

In [15]:
df['Loan_Amount_Term'].unique() #numeric data

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [16]:
df['Credit_History'].unique() #binary data

array([ 1.,  0., nan])

In [17]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [18]:
df["Married"].fillna(df['Married'].mode()[0],inplace=True)

In [19]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [20]:
df["Dependents"].fillna(df['Dependents'].mode()[0],inplace=True)

In [21]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               0
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [22]:
df["Self_Employed"].fillna(df['Self_Employed'].mode()[0],inplace=True)

In [23]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [24]:
df["Loan_Amount_Term"].fillna(df['Loan_Amount_Term'].mode()[0],inplace=True)

In [25]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term      0
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [26]:
df["Credit_History"].fillna(df['Credit_History'].mode()[0],inplace=True)

In [27]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [28]:
df["Gender"].fillna(df['Gender'].mode()[0],inplace=True)

In [29]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [30]:
df["LoanAmount"].fillna(df['LoanAmount'].mean(),inplace=True) #since LoanAmount is numeric, we fill that data with mean

In [31]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [32]:
df.duplicated().sum()

0

## Data Transformation

In [33]:
df['TotalIncome'] = df['ApplicantIncome'] + df['CoapplicantIncome']  #Attribute Construction

In [34]:
df.drop(columns=['ApplicantIncome','CoapplicantIncome'],inplace=True)

In [35]:
df['Gender'].replace('Male',int(0),inplace=True) # changing binary string data to binary int data
df['Gender'].replace('Female',int(1),inplace=True)
df['Married'].replace('No',0,inplace=True)
df['Married'].replace('Yes',1,inplace=True)
df['Loan_Status'].replace('N',0,inplace=True)
df['Loan_Status'].replace('Y',1,inplace=True)
df['Credit_History'].replace(1.0,1,inplace=True)
df['Credit_History'].replace(0.0,0,inplace=True)
df['Self_Employed'].replace('Yes',1,inplace=True)
df['Self_Employed'].replace('No',0,inplace=True)
df['Education'].replace('Graduate',1,inplace=True)
df['Education'].replace('Not Graduate',0,inplace=True)

In [36]:
df

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0    LP001002       0        0          0          1              0   
1    LP001003       0        1          1          1              0   
2    LP001005       0        1          0          1              1   
3    LP001006       0        1          0          0              0   
4    LP001008       0        0          0          1              0   
..        ...     ...      ...        ...        ...            ...   
609  LP002978       1        0          0          1              0   
610  LP002979       0        1         3+          1              0   
611  LP002983       0        1          1          1              0   
612  LP002984       0        1          2          1              0   
613  LP002990       1        0          0          1              1   

     LoanAmount  Loan_Amount_Term  Credit_History Property_Area  Loan_Status  \
0    146.412162             360.0             1.0         Urban            1   
1    128.000000             360.0             1.0         Rural            0   
2     66.000000             360.0             1.0         Urban            1   
3    120.000000             360.0             1.0         Urban            1   
4    141.000000             360.0             1.0         Urban            1   
..          ...               ...             ...           ...          ...   
609   71.000000             360.0             1.0         Rural            1   
610   40.000000             180.0             1.0         Rural            1   
611  253.000000             360.0             1.0         Urban            1   
612  187.000000             360.0             1.0         Urban            1   
613  133.000000             360.0             0.0     Semiurban            0   

     TotalIncome  
0         5849.0  
1         6091.0  
2         3000.0  
3         4941.0  
4         6000.0  
..           ...  
609       2900.0  
610       4106.0  
611       8312.0  
612       7583.0  
613       4583.0  

[614 rows x 12 columns]

In [37]:
df['Dependents'].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [38]:
from sklearn import preprocessing
label_encoder_dependents = preprocessing.LabelEncoder()
df['Dependents']= label_encoder_dependents.fit_transform(df['Dependents'])
df['Dependents'].unique()

array([0, 1, 2, 3])

In [39]:
label_encoder_pa = preprocessing.LabelEncoder()
df['Property_Area']= label_encoder_pa.fit_transform(df['Property_Area'])
df['Property_Area'].unique()

array([2, 0, 1])

In [40]:
df

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001002       0        0           0          1              0   
1    LP001003       0        1           1          1              0   
2    LP001005       0        1           0          1              1   
3    LP001006       0        1           0          0              0   
4    LP001008       0        0           0          1              0   
..        ...     ...      ...         ...        ...            ...   
609  LP002978       1        0           0          1              0   
610  LP002979       0        1           3          1              0   
611  LP002983       0        1           1          1              0   
612  LP002984       0        1           2          1              0   
613  LP002990       1        0           0          1              1   

     LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  Loan_Status  \
0    146.412162             360.0             1.0              2            1   
1    128.000000             360.0             1.0              0            0   
2     66.000000             360.0             1.0              2            1   
3    120.000000             360.0             1.0              2            1   
4    141.000000             360.0             1.0              2            1   
..          ...               ...             ...            ...          ...   
609   71.000000             360.0             1.0              0            1   
610   40.000000             180.0             1.0              0            1   
611  253.000000             360.0             1.0              2            1   
612  187.000000             360.0             1.0              2            1   
613  133.000000             360.0             0.0              1            0   

     TotalIncome  
0         5849.0  
1         6091.0  
2         3000.0  
3         4941.0  
4         6000.0  
..           ...  
609       2900.0  
610       4106.0  
611       8312.0  
612       7583.0  
613       4583.0  

[614 rows x 12 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Loan_ID           614 non-null    object 
 1   Gender            614 non-null    int64  
 2   Married           614 non-null    int64  
 3   Dependents        614 non-null    int32  
 4   Education         614 non-null    int64  
 5   Self_Employed     614 non-null    int64  
 6   LoanAmount        614 non-null    float64
 7   Loan_Amount_Term  614 non-null    float64
 8   Credit_History    614 non-null    float64
 9   Property_Area     614 non-null    int32  
 10  Loan_Status       614 non-null    int64  
 11  TotalIncome       614 non-null    float64
dtypes: float64(4), int32(2), int64(5), object(1)
memory usage: 52.9+ KB
